# Generated by Django 6.0.4 on 2026-04-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_booknote_experience_reference_writingentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='writingentry',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
