# Generated by Django 6.0.4 on 2026-04-14 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_slug_alter_writingentry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reference',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('introduction', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='project-screenshots/')),
                ('image_url', models.URLField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='portfolio.project')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
