# Generated by Django 6.0.4 on 2026-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_capability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=180)),
                ('institution', models.CharField(max_length=180)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('period', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'institution'],
            },
        ),
    ]
