# Generated by Django 6.0.4 on 2026-04-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="booknote",
            name="cover",
            field=models.FileField(blank=True, upload_to="book-covers/"),
        ),
    ]
