# Generated by Django 6.0.4 on 2026-04-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_booknote_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="writingentry",
            name="cover",
            field=models.FileField(blank=True, upload_to="writing-covers/"),
        ),
        migrations.CreateModel(
            name="WritingAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("image", models.FileField(upload_to="writing-assets/")),
                ("alt_text", models.CharField(blank=True, max_length=180)),
                ("caption", models.CharField(blank=True, max_length=220)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entry", models.ForeignKey(on_delete=models.CASCADE, related_name="assets", to="portfolio.writingentry")),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
    ]
